### ISSUE TITLE
Random seed setting

### ISSUE THREAD

**Issue by Taylor-Liu** [inoryy/reaver#13]
Hi, inoryy. 
How did you set your random seed, as shown in your learning curves?

**Comment by inoryy** [comment]
Hello, the learning curves are shown for different (non-fixed) random seeds, there was no need to set them manually.

If you want to do it yourself, add these lines somewhere before graph vars are initialized:

```python
tf.set_random_seed(1234)
np.random.seed(1234)
```

However note that due to [how CUDA works internally](https://github.com/tensorflow/tensorflow/issues/12871) you might still experience non-deterministic behavior.

**Comment by Taylor-Liu** [comment]
Thanks!
