### ISSUE TITLE
Issue with running on google colab

### ISSUE THREAD

**Issue by jackylee1** [inoryy/reaver#22]
the last step,it shows:
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by inoryy** [comment]
That's ok, if you look at the original colab output you'll see those errors as well.
Happens because google's tcmalloc is uninstalled (conflicts with SC2), but the preload config isn't updated.
![screenshot from 2019-01-27 13-21-52](https://user-images.githubusercontent.com/195271/51800370-9121ca80-2236-11e9-94c8-5c0aeafa3e2e.png)

**Comment by jackylee1** [comment]
but i didn't see any output

**Comment by inoryy** [comment]
Ok, I'll see if I can replicate

**Comment by inoryy** [comment]
@jackylee1 ok I was able to replicate, going to re-run whole notebook just in case, but for a quickfix replace last line with:

```
!python -m reaver.run --env MoveToBeacon --agent a2c --n_envs 2 --log_freq 25 --n_updates 5000 2> stderr.log
```

**Comment by inoryy** [comment]
I've noticed that some of my latest changes slowed down learning process on 1-4 envs, so I'm going to lock colab to the initial 2.0 version. I've updated the notebook and re-ran it, works fine.
If you want to use the latest reaver version then use the command above, but note that training on colab could take up to 2 hours.
